"use strict";
const fs = require("fs");
const path = require("path");
const assert = require("assert");
const root = path.resolve(__dirname, "..");
const version = "jm-fluxo-operacional-v17-motorista-modo-rua-com-acessos";
const flow = fs.readFileSync(path.join(root, "js", "motorista-simple-flow.js"), "utf8");
const css = fs.readFileSync(path.join(root, "css", "style.css"), "utf8");
const html = fs.readFileSync(path.join(root, "motorista.html"), "utf8");
assert.ok(flow.includes(version), "motorista-simple-flow.js deve conter V16");
assert.ok(html.includes(version), "motorista.html deve carregar V16");
assert.ok(flow.includes("MODO RUA"), "Modo Rua precisa existir");
assert.ok(flow.includes("TIRAR FOTO") && flow.includes("GALERIA") && flow.includes("NÃO TENHO FOTOS"), "Fotos devem ter câmera, galeria e justificativa única");
assert.ok(flow.includes("ASSINAR NA TELA") && flow.includes("JUSTIFICAR SEM ASSINATURA"), "Assinatura deve ser etapa separada com justificativa");
assert.ok(flow.includes("DESPESA"), "Despesa rápida deve continuar acessível");
assert.ok(flow.includes("driver-show-all"), "Modo técnico deve continuar disponível");
assert.ok(css.includes("driver-street-mode") && css.includes("driver-street-primary"), "CSS do Modo Rua deve existir");
assert.ok(css.includes("#driverAppView .grid > .panel:not(#driverSimpleShell)"), "Modo Rua deve esconder painéis técnicos quando não solicitados");
console.log("PASS motorista-modo-rua-v16.test.js");
