"use strict";
const fs = require("fs");
const path = require("path");
const assert = require("assert");
const root = path.resolve(__dirname, "..");
const version = "jm-fluxo-operacional-v26-cache-refresh";
const flow = fs.readFileSync(path.join(root, "js", "motorista-simple-flow.js"), "utf8");
const css = fs.readFileSync(path.join(root, "css", "style.css"), "utf8");
const html = fs.readFileSync(path.join(root, "motorista.html"), "utf8");
assert.ok(flow.includes(version), "motorista-simple-flow.js deve conter V19");
assert.ok(html.includes(version), "motorista.html deve carregar V19");
assert.ok(flow.includes("driver-popular-mode"), "Modo popular precisa existir");
assert.ok(flow.includes("TIRAR FOTO") && flow.includes("GALERIA") && flow.includes("SEM FOTO"), "Fotos devem ter câmera, galeria e justificativa simples");
assert.ok(flow.includes("ASSINAR") && flow.includes("NÃO ASSINOU"), "Assinatura deve ser etapa separada com justificativa");
assert.ok(flow.includes("DESPESA RÁPIDA"), "Despesa rápida deve continuar acessível");
assert.ok(flow.includes("driver-show-all"), "Modo técnico deve continuar disponível");
assert.ok(css.includes("driver-popular-mode") && css.includes("driver-popular-primary"), "CSS do Modo Popular deve existir");
assert.ok(css.includes("#driverAppView .grid > .panel:not(#driverSimpleShell)"), "Modo popular deve esconder painéis técnicos quando não solicitados");
console.log("PASS motorista-modo-rua-v16.test.js");
