"use strict";
const fs = require("fs");
const path = require("path");
const assert = require("assert");
const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "motorista.html"), "utf8");
const js = fs.readFileSync(path.join(root, "js", "motorista-simple-flow.js"), "utf8");
const css = fs.readFileSync(path.join(root, "css", "style.css"), "utf8");
const sw = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
const version = "jm-fluxo-operacional-v13-motorista-sequencial-automatico";
assert.ok(html.includes(version), "motorista.html deve carregar V13");
assert.ok(sw.includes(version), "service-worker deve usar cache V13");
assert.ok(js.includes("STATUS_NEXT"), "V13 deve ter sequência automática de status");
assert.ok(js.includes("runStatus"), "V13 deve salvar/avançar status por ação grande");
assert.ok(js.includes("firstMissingForStatus"), "V13 deve localizar primeira pendência relevante");
assert.ok(js.includes("openJustificationFor"), "V13 deve abrir justificativa quando a prova não existir");
assert.ok(js.includes("ASSINAR / JUSTIFICAR"), "V13 deve tratar assinatura/justificativa como ação principal");
assert.ok(js.includes("saveProofDraft"), "V13 deve preservar salvamento de rascunho de provas");
assert.ok(js.includes("choosePhotoInput"), "V13 deve manter câmera/galeria no fluxo guiado");
assert.ok(css.includes("driver-sequential-mode"), "CSS V13 deve aplicar modo sequencial");
assert.ok(css.includes("driver-seq-primary"), "CSS V13 deve ter botão grande de próxima ação");
assert.ok(css.includes("driver-seq-rule"), "CSS V13 deve destacar prova ou justificativa obrigatória");
console.log("PASS motorista-sequencial-v13.test.js");
