"use strict";
const fs = require("fs");
const path = require("path");
const assert = require("assert");
const root = path.resolve(__dirname, "..");
const version = "jm-fluxo-operacional-v26-cache-refresh";
const flow = fs.readFileSync(path.join(root, "js", "motorista-simple-flow.js"), "utf8");
const driver = fs.readFileSync(path.join(root, "js", "motorista.js"), "utf8");
const sw = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
const css = fs.readFileSync(path.join(root, "css", "style.css"), "utf8");
const html = fs.readFileSync(path.join(root, "motorista.html"), "utf8");
assert(flow.includes(version), "motorista-simple-flow deve carregar versão V20");
assert(driver.includes(version), "motorista.js deve carregar versão V20");
assert(html.includes(version), "motorista.html deve chamar assets com V20");
assert(flow.includes("driverStreetMissingBtn"), "Modo Rua precisa ter botão clicável para pendências");
assert(flow.includes("addressText"), "Modo Rua precisa evitar [object Object] em origem/destino");
assert(driver.includes("notifyDriverNewCall"), "motorista.js precisa avisar novo chamado");
assert(driver.includes("requestDriverNotifications"), "motorista.js precisa pedir permissão de notificação");
assert(sw.includes("notificationclick"), "service-worker precisa tratar clique da notificação");
assert(css.includes("driver-popular-missing-btn"), "CSS precisa destacar botão de pendência clicável");
console.log("PASS motorista-pendencias-notificacoes-v20.test.js");
